version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.24
    steps:
      - checkout
      - run: go build .
      - store_artifacts:
          path: terraform-provider-kafka
          destination: terraform-provider-kafka

  setup-kafka:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            docker compose up --detach
            docker compose ps
  test:
    docker:
      - image: cimg/go:1.24
        environment:
          TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - setup_remote_docker
      - run: make test
      - run: go install github.com/jstemmer/go-junit-report/v2@latest
      - run: mkdir -p $TEST_RESULTS
      - run: docker compose ps
      - run:
          name: Run Tests
          command: |
            trap "docker ps -a && go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make testacc | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - setup-kafka
      - test
